changelog:
  exclude:
    labels:
      - Ignore for release
    authors:
  categories:
    - title: Exciting New Features 🎉
      labels:
        - Feature
    - title: Fixes 🔧
      labels:
        - Fix
    - title: Continuous Integration 🔧
      labels:
        - CI
    - title: Other Changes
      labels:
        - '*'
