name: General CI

on:
  push:
    branches: [master]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  runs-on: ubuntu-latest
  install-dependencies:
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

  build:
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npm run build

  client-bundle-size:
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2

      # https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout
      - name: override CI_COMMIT_SHA
        if: github.event_name == 'pull_request'
        run: echo "CI_COMMIT_SHA=${{ github.event.pull_request.head.sha}}" >> $GITHUB_ENV

      - name: Run BundleMon
        run: npx bundlemon
        env:
          BUNDLEMON_PROJECT_ID: ${{ secrets.BUNDLEMON_PROJECT_ID }}
          BUNDLEMON_PROJECT_APIKEY: ${{ secrets.BUNDLEMON_PROJECT_APIKEY }}
          BUNDLEMON_GITHUB_TOKEN: ${{ secrets.BUNDLEMON_GITHUB_TOKEN }}

  code-quality:
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: npm run test

      - name: Run prettier
        run: npx prettier --check .

      - name: Run linter
        run: npm run lint

  chromatic-deployment:
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v1

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing