name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  pr_commented:
    name: PR comment
    if: ${{ contains(github.event.comment.body, '/deploy') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
          echo Body is $BODY
        env:
          NUMBER: ${{ github.event.issue.number }}
          BODY: ${{ github.event.comment.body }}
          IS_TRIGGER: ${{ contains(github.event.comment.body, '/deploy') }}
