name: Create Notion Journal Entry
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call the API route
        run: |
          curl --request POST \
          --url 'https://andrew-notion-api.vercel.app/api/trigger-journal-entry-creation' \
          --header 'Authorization: Bearer ${{ secrets.NOTION_API_SECRET_KEY }}'
