name: Pull Request CI
on:
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_dispatch:
env:
  node_version: 16.5.0
  pnpm_version: 7.14.0
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.pnpm_version }}
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: pnpm
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            **/.cache/Cypress
            **/node_modules
          key: node-modules-${{ hashFiles('./pnpm-lock.yaml') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i
      - name: Run linter
        run: pnpm lint
  component_tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.pnpm_version }}
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            **/.cache/Cypress
            **/node_modules
          key: node-modules-${{ hashFiles('./pnpm-lock.yaml') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i
      - name: Run component tests
        run: pnpm test:run:ct
