name: Pull Request CI
on:
  pull_request:
    types: [synchronize, opened, reopened]
env:
  node_version: 16.5.0
  pnpm_version: 7.6.0
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ env.pnpm_version }}
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: pnpm
      - name: Install dependencies
        run: npx pnpm i
      - name: Run linter
        run: npx pnpm lint
