name: Pull Request CI
on:
  pull_request:
    types: [synchronize, opened, reopened]
env:
  node_version: 14
jobs:
  lint:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      - name: Install dependencies
        run: npx pnpm i -r
      - name: Run linter
        run: npx pnpm lint
