name: Pull Request CI
on:
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_dispatch:
env:
  node_version: 16.5.0
  pnpm_version: 7.14.0
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.pnpm_version }}
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Run linter
        run: pnpm lint
