name: Pull Request CI
on:
  pull_request:
    types: [synchronize, opened, reopened]
env:
  node_version: 14
  pnpm_version: 6.30.1
jobs:
  lint:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set pnpm
        uses: pnpm/action-setup@2.1.0
        with:
          version: ${{ env.pnpm_version }}
          run_install: true
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: pnpm
      - name: Run linter
        run: npx pnpm lint
